import { useEffect, useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { AddonContext, HostAPI } from '@wealthfolio/addon-sdk';
import { ADDON_ID, fetchAccountSummary, fetchTrading212, importWithDuplicateDetection, readConfig, saveConfig, SECRET_KEY, toActivityImports, type Config } from './utils/trading212';
import './style.css';

let context: AddonContext;
function Page() { return <QueryClientProvider client={context.api.query.getClient() as QueryClient}><TradingPage api={context.api} /></QueryClientProvider>; }
export function TradingPage({ api }: { api: HostAPI }) {
  const [config, setConfig] = useState<Config>({ environment: 'live', accountId: '' });
  const [key, setKey] = useState(''); const [secret, setSecret] = useState(''); const [hasCredentials, setHasCredentials] = useState(false); const [accounts, setAccounts] = useState<any[]>([]);
  const [newAccountName, setNewAccountName] = useState('Trading 212');
  const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([readConfig(api), api.accounts.getAll(), api.secrets.get(SECRET_KEY)]).then(([c, a, credential]) => { setConfig(c); setAccounts(a); if (credential) { setHasCredentials(true); setStatus('Credentials saved securely.'); } }); }, [api]);
  async function connect() { if ((!key.trim() || !secret.trim()) && !hasCredentials) return setStatus('Enter both API key and API secret.'); setBusy(true); setStatus('Testing credentials…'); try { if (key.trim() && secret.trim()) { await api.secrets.set(SECRET_KEY, btoa(`${key.trim()}:${secret.trim()}`)); setHasCredentials(true); } const data = await fetchAccountSummary(api.network, config.environment); const next = { ...config, accountId: config.accountId, brokerAccountId: String(data.id), currency: data.currency }; setConfig(next); await saveConfig(api, next); setStatus(`Connected to account ${data.id} (${data.currency}).`); } catch (e) { setStatus(e instanceof Error ? e.message : 'Connection failed.'); } finally { setBusy(false); } }
  async function sync() { if (!config.accountId) return setStatus('Connect and select a Wealthfolio account first.'); setBusy(true); setStatus('Fetching Trading 212 history…'); try { const data = await fetchTrading212(api.network, config.environment); const result = await importWithDuplicateDetection(api, toActivityImports(data, config.accountId)); const next = { ...config, lastSync: new Date().toISOString() }; setConfig(next); await saveConfig(api, next); setStatus(`Sync complete: ${result.imported} imported, ${result.duplicates} duplicates, ${result.skipped} skipped.`); } catch (e) { api.logger.error(`[${ADDON_ID}] sync failed: ${String(e)}`); setStatus(e instanceof Error ? e.message : 'Sync failed.'); } finally { setBusy(false); } }
  async function createAccount() { if (!newAccountName.trim()) return setStatus('Enter a name for the new Wealthfolio account.'); setBusy(true); try { const summary = config.brokerAccountId && config.currency ? { id: Number(config.brokerAccountId), currency: config.currency } : await fetchAccountSummary(api.network, config.environment); const created = await api.accounts.create({ name: newAccountName.trim(), accountType: 'SECURITIES', currency: summary.currency, isDefault: false, isActive: true, trackingMode: 'TRANSACTIONS', provider: 'Trading 212', providerAccountId: String(summary.id) }); const next = { ...config, accountId: created.id, brokerAccountId: String(summary.id), currency: summary.currency }; setAccounts((current) => [...current, created]); setConfig(next); await saveConfig(api, next); setStatus(`Created and mapped ${created.name} (${summary.currency}).`); } catch (e) { api.logger.error(`[${ADDON_ID}] account creation failed: ${String(e)}`); setStatus(e instanceof Error ? e.message : 'Account creation failed.'); } finally { setBusy(false); } }
  return <main className="page"><header><div><div className="eyebrow">BROKER CONNECTION</div><h1>Trading 212</h1><p>Import orders, dividends and cash movements directly from your Trading 212 account.</p></div><button className="primary" onClick={sync} disabled={busy || !config.accountId}>↻ Sync now</button></header><section className="card"><h2>Connection</h2><p className="muted">Your credentials are stored in Wealthfolio’s secure keyring and never persisted in addon settings.</p><div className="grid"><label>Environment<select value={config.environment} onChange={(e) => setConfig({ ...config, environment: e.target.value as Config['environment'] })}><option value="live">Live</option><option value="demo">Demo</option></select></label><label>API key<input value={key} onChange={(e) => setKey(e.target.value)} placeholder="Trading 212 API key" /></label><label>API secret<input type="password" value={secret} onChange={(e) => setSecret(e.target.value)} placeholder="Trading 212 API secret" /></label></div><button onClick={connect} disabled={busy}>{busy ? 'Working…' : 'Save & test connection'}</button></section><section className="card"><h2>Wealthfolio account</h2><p className="muted">All imported activities will be added to this account.</p>{accounts.length > 0 && <select value={config.accountId} onChange={async (e) => { const next = { ...config, accountId: e.target.value }; setConfig(next); await saveConfig(api, next); }}><option value="">Select an account…</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select>}<div className="wizard"><strong>{accounts.length ? 'Create another account' : 'Create your Wealthfolio account'}</strong><span className="muted">Creates a transaction-tracked securities account and maps it to this Trading 212 account.</span><input value={newAccountName} onChange={(e) => setNewAccountName(e.target.value)} placeholder="Account name" /><button onClick={createAccount} disabled={busy || !newAccountName.trim()}>Create and map account</button></div></section><section className="notice">{status || (config.lastSync ? `Last sync: ${new Date(config.lastSync).toLocaleString()}` : 'Connect Trading 212 to begin.')}</section><footer><a href="https://helpcentre.trading212.com/hc/en-us/articles/14584770928157-Trading-212-API-key" target="_blank">How to create an API key ↗</a><span>Trading 212 API is read-only for this addon.</span></footer></main>;
}
export default function enable(ctx: AddonContext) { context = ctx; ctx.router.add({ id: ADDON_ID, path: `/addons/${ADDON_ID}`, component: Page }); ctx.onDisable(() => { context = undefined!; }); }
